#.circleci/config.yml

version: 2.0
jobs:
  build:
    docker:
      - image: jruby:9.3
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: curl ifconfig.me
